
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      

    - name: Install dependencies
      run: |
        if [ -e yarn.lock ]; then
        yarn install --frozen-lockfile
        elif [ -e package-lock.json ]; then
        npm ci
        else
        npm i
        fi

    - name: Build my App  
      run: npm run build
      env:
        NEXT_PUBLIC_BASE_PATH: /youtube-2020-august-github-pages-github-actions
    - run: npm run export
      env:
        NEXT_PUBLIC_BASE_PATH: /youtube-2020-august-github-pages-github-actions
    - run: touch ./out/.nojekyll
    
    - name: Deploy 🚀
      uses: actions/checkout@v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: out # The folder the action should deploy.
